// import { ChangeEvent, useState } from 'react'
import DefaultTemplate from 'templates/Default'
import useDeckContext from 'hooks/useDeckContext'
import Button from 'components/Button'
import Head from 'next/head';
import * as S from './styles'
import Heading from 'components/Heading'
import { useEffect, useState } from 'react'
import { getSessionStorage, setSessionStorage } from 'hooks/useSession'
import Cards from 'components/Cards'
import { useRouter } from 'next/router'
import { DeckService } from 'service/DeckService'

export default function DeckPage() {
  const { 
    cards, 
    setCards, 
    drawNewCard, 
    counterDraw, 
    setCounterDraw
  } = useDeckContext();
  const [name, setName] = useState('');

  const router = useRouter();

  function shuffleCards() {
    const newArray = [...cards]
    const length = newArray.length
  
    for (let start = 0; start < length; start++) {
      const randomPosition = Math.floor((newArray.length - start) * Math.random())
      const randomItem = newArray.splice(randomPosition, 1)
  
      newArray.push(...randomItem)
    }
    setCards(newArray);
    setSessionStorage('cards', newArray);
  }
  
  async function drawCard() {
    try {
      if(counterDraw < 3){
        const res = await drawNewCard();
        const newCard = res.cards;

        var currentArrayOfCards = cards;
        currentArrayOfCards = [
          ...currentArrayOfCards,
          newCard
        ]
        setCards(currentArrayOfCards);

        setSessionStorage('cards', currentArrayOfCards);
        cards.push(newCard);
        setCounterDraw(oldstate => oldstate + 1);
      }
    } catch (error) {      
      router.push('/');
    }
  }

  async function getMyDeck() {
    await DeckService.new();
  }

  useEffect(() => {
    getMyDeck();
  },[])

  useEffect(() => {
    const sessionUserName = getSessionStorage('userName');
    if(!sessionUserName) {
      router.push('/');
      return;
    }
    setName(sessionUserName);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultTemplate>
        <Heading name={name} />
        <S.Content>
          {counterDraw > 2 && <S.MaxCards>Máximo de cartas atingido! Tente embaralhar as cartas...</S.MaxCards>}
          <Cards cards={cards} />

          <S.NumberOfCards>Você tem {cards.length} cartas no deck</S.NumberOfCards>

          <Button 
            type="button"
            onClick={() => drawCard()}
            disabled={counterDraw > 2}
            >
            <span>Draw</span>
          </Button>
          
          <Button type="button" onClick={() => shuffleCards()}>
            <span>Shuffle</span>
          </Button>

        </S.Content>
      </DefaultTemplate>
    </>
  )
}

/*

  Construir uma tela que exibe cinco cartas, o conteúdo dessas cartas deve ser alimentado via API.

  Cada carta deve conter pelo menos: nome, imagem, descrição e um valor aleatório de 0 a 10 que podemos chamar de pontos.

  Ao acessar a primeira página ele deve digitar um nome e clicar em ver cartas.

  Na tela seguinte ele visualiza as 5 cartas e o  seu nome no canto superior direito.

  Na tela de cartas ele tem dois botões, onde um deles permite puxar uma nova carta aleatoriamente, ele pode apertar apenas 3 vezes.

  As cartas nunca são descartadas, caso ele puxe 3 novas cartas ele estará visualizando 8 cartas.

  O segundo botão permite a ele embaralhar a ordem das cartas que está visualizando.

*/