import Button from 'components/Button'
import DefaultTemplate from 'templates/Default';
import useDeckContext from 'hooks/useDeckContext';
import { ChangeEvent, useState } from 'react';
import Head from 'next/head';
import { setSessionStorage } from 'hooks/useSession';
import { useRouter } from 'next/router';
import TextField from 'components/TextField';

export default function Home() {
  const { getNewDeck, error, setError } = useDeckContext();
  const router = useRouter();
  const [inputValue, setInputValue] = useState('');

  function handleInputChange(e: ChangeEvent<HTMLInputElement>) {
    setInputValue(e.target.value);
  }

  function handleInputFocus() {
    if(inputValue.length === 0) {
      setError({nome: 'Campo obrigatório'})
    }
  }
  
  async function startWithNewDeck() {
    setError({nome: ''});
    if(inputValue.length <= 3){
      setError({nome: 'Nome deve possuir no mínimo 3 caracteres'})
      return;
    }
    setSessionStorage('userName', inputValue);
    await getNewDeck();
    router.push('/mydeck');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultTemplate>
        <TextField 
          type="text" 
          label="Nome" 
          placeholder="Inserir Nome" 
          onChange={(e) => handleInputChange(e)} 
          value={inputValue} 
          onFocus={() => {handleInputFocus()}}
          errorMessage={!!error['nome'] && error['nome']}
          />
        <Button type="button" onClick={startWithNewDeck} disabled={inputValue.length === 0}>
          <span>Start</span>
        </Button>
      </DefaultTemplate>
    </>
  )
}