import Head from 'next/head'
import { Main } from 'components/Main'
import { Container } from 'components/Container'
import Button from 'components/Button'
// import api from 'service/api'

export default function Home() {
  function shuffleCards() {
    //api.;
    return;
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Main>
          <h1>
            Welcome
          </h1>
          <Button type="button" onClick={shuffleCards}>
            <span>SHUFFLE</span>
          </Button>
        </Main>
      </Container>
    </>
  )
}
